### ISSUE TITLE
Teaching Us About Github

### ISSUE THREAD

**Issue by jsrlowery** [ReedRGale/Chess#1]
I'm going to look up how to use Github. I'll post essential information here.

**Comment by jsrlowery** [comment]
I'm getting the idea that you need to download git to effectively use github:

http://git-scm.com/downloads

**Comment by jsrlowery** [comment]
What is a branch?

So we see this thing called a branch from time to time so I feel it needs to be explained. A repository starts with a master branch which stores all the files within it. When we create a branch, we essentially create an exact copy of the master branch that can be edited separately. 

This allows for simple edits to be tested and ideas to be kept separate from the main production until we know it works. Then we can merge it back with the master branch.

**Comment by jsrlowery** [comment]
Mostly for Lesley:

So there are more things to learn about issues than what he had before.

For instance there are those things to the right of the comments. First is "labels." Those allow people to, at a glance, distinguish one type of issue from another. From comments to questions, bugs to requests for help, we can label issues to make them easier to sum up in a glance. Use the context-sensitive great menu to access the dropdown menu to add a label.

Milestones allow us to sum up quickly the progress made in an issue and to separate the issue into smaller issues. To assign a new milestone, click on the context-sensitive gear menu. Then input a name for a milestone. I don't know what else you can do with those, but it seems like an issue within an issue.

Assignee on the side seems pretty self-explanatory.

**Comment by Leslacoil** [comment]
I am going to try to make an update to the 'Master' branch.

**Comment by jsrlowery** [comment]
What are commits and how do we make them?

So when you save a file to the repository it's called "committing" it. These commits allow us to track the history of our edits because whenever you commit you are requested to leave a reason for your edits. These can include points as far as why you made the edit, what edits were made, who made the edits and when.

First you click on the file you wish to edit from the main repository branch. Then there should be the option to edit the file with the pencil icon that can be located in the upper right-hand corner of the window in the middle of the browser. Then, after making changes to the file, you can make the commit and write the message in the window below the editor.

To practice, the readme.txt in the master branch can be edited by clicking on it then clicking on the pencil icon. I'd recommend trying this to practice committing.

**Comment by jsrlowery** [comment]
So what is pulling? Pulling is how we ask people whether the changes we've made in our branches are worth making part of the main branch. On the far right side of the browser should be a "pull requests" section. To make a new pull request, simply push the green button on the middle section and select a branch. The diffs should be marked in red and will allow for comparison between the selected branch and the master.

Then, completing the request is as simple as pushing a button.

**Comment by jsrlowery** [comment]
I'm reading this guide right now:  https://guides.github.com/introduction/getting-your-project-on-github/

It should solve our current problem of using Github to upload code.
